
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.example.practicakotli.Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DECIMAL = 9;
  public static final int MENOS = 5;
  public static final int UMENOS = 10;
  public static final int ENTERO = 8;
  public static final int POR = 6;
  public static final int EOF = 0;
  public static final int MAS = 4;
  public static final int PAR2 = 3;
  public static final int PAR1 = 2;
  public static final int error = 1;
  public static final int DIVISION = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAR1",
  "PAR2",
  "MAS",
  "MENOS",
  "POR",
  "DIVISION",
  "ENTERO",
  "DECIMAL",
  "UMENOS"
  };
}

